spring:
  application:
    name: createusers

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/test

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include=*:
